MAKAIRA-3320 [Component] Update Buttons
MakairaIO/app-boilerplate-nextjs pull request #10
Opened 2023-03-09 07:56 UTC by datlieu110

2023-03-15 08:12 UTC, JanMaeg requested changes

2023-03-15 08:12 UTC, JanMaeg commented on src/components/Button/Button.tsx
> +            <div className={csx(styles.icon, 'icon')}>
Please always use CSS-Modules Classes and do not assign class-names directly.

2023-03-15 08:12 UTC, JanMaeg commented on src/pages/example.tsx
> +        <button>Back to homepage</button>
Please switch these button to our buttons and not the default browser ones. Looks weird if there some unstyled buttons.

2023-03-19 12:55 UTC, MrAvantiC commented
Closed in favour of https://github.com/MakairaIO/app-boilerplate-nextjs/pull/8

2023-03-19 12:55 UTC, closed without merging