MAKAIRA-3323 [Component] Data Table, Pagination
MakairaIO/app-boilerplate-nextjs pull request #11
Opened 2023-03-09 09:51 UTC by datlieu110

2023-03-15 08:16 UTC, JanMaeg requested changes

2023-03-15 08:16 UTC, JanMaeg commented on src/components/Pagination/Pagination.module.scss
> +
Please change the background to be transparent for pagination buttons.

```suggestion
  background: transparent;
```

2023-03-15 08:16 UTC, JanMaeg commented on src/components/Pagination/Pagination.module.scss
> +
Please change the background to be transparent for pagination buttons.

```suggestion
  background: transparent;
```

2023-03-19 12:55 UTC, MrAvantiC commented
Closed in favour of https://github.com/MakairaIO/app-boilerplate-nextjs/pull/8

2023-03-19 12:55 UTC, closed without merging