MAKAIRA-3360 [Component] Dashboard App Menu
MakairaIO/app-boilerplate-nextjs pull request #14
Opened 2023-03-10 10:41 UTC by nfqphihungnguyen

2023-03-15 08:25 UTC, JanMaeg requested changes

2023-03-15 08:25 UTC, JanMaeg commented on src/components/AppMenu/AppMenu.tsx
> +const AppMenu: React.FC<AppMenuProps> = ({ icon, text, badge }) => {
Change the name of the component to `AppTitle`

2023-03-15 08:25 UTC, JanMaeg commented on src/components/AppMenu/AppMenu.tsx
> +  badge?: React.ReactElement
Badge should only allow simple strings. We don't support and need passing components to the badge.

2023-03-15 08:25 UTC, JanMaeg commented on src/components/AppMenu/AppMenu.tsx
> +      {badge && <span className={styles.badge}>{badge}</span>}
Styling of the badge is missing.

2023-03-19 12:55 UTC, MrAvantiC commented
Closed in favour of https://github.com/MakairaIO/app-boilerplate-nextjs/pull/8

2023-03-19 12:55 UTC, closed without merging