MAKAIRA-3363 [Component ] Modal, ShadowScroll
MakairaIO/app-boilerplate-nextjs pull request #17
Opened 2023-03-14 06:59 UTC by thuanlemarmalade

2023-03-15 08:58 UTC, JanMaeg requested changes

2023-03-15 08:58 UTC, JanMaeg commented on src/components/Modal/Modal.module.scss
> +  .modal {
The modal is not correctly placed. It should be in the center of the screen.

2023-03-15 08:58 UTC, JanMaeg commented on src/components/Modal/Modal.module.scss
> +  .modalFooter {
- [ ] Footer should also be displayed correctly when no footer text is given in the props. Same applies for the header.
- [ ] Footer and Header should use the correct font

2023-03-19 12:54 UTC, MrAvantiC commented
Closed in favour of https://github.com/MakairaIO/app-boilerplate-nextjs/pull/8

2023-03-19 12:54 UTC, closed without merging